In [1]:
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir) 

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import json
import networkx as nx
import lib.build_graph as bg

/home/zjliao/dsc180a/lib/create_database.py:19: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 19 of the file /home/zjliao/dsc180a/lib/create_database.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(site.text)


In [8]:
cfg = json.load(open('/home/zjliao/dsc180a/config/data-params.json'))
print(cfg, '\n')
A, apis, apks = bg.buildA_matrix(**cfg)

{'benign_src': '/home/zjliao/dsc180a/data/smali', 'mal_src': '/datasets/dsc180a-wi20-public/Malware/amd_data_smali', 'num_b': 2, 'num_m': 2} 

Build A
get info
get smali
get smali
check malware
get smali
get smali
got info
47212


In [9]:
apis

0        android/view/View;-><init>(Landroid/content/Co...
1                        android/graphics/Rect;-><init>()V
2                           android/os/Handler;-><init>()V
3        android/view/View;->onDraw(Landroid/graphics/C...
4        android/graphics/Canvas;->getClipBounds(Landro...
                               ...                        
47207    org/joda/time/format/PeriodFormatterBuilder;->...
47208    org/joda/time/format/PeriodFormatterBuilder;->...
47209    org/joda/time/format/PeriodFormatterBuilder;->...
47210    org/joda/time/format/PeriodFormatterBuilder;->...
47211    org/joda/time/format/PeriodFormatterBuilder;->...
Length: 47212, dtype: object

In [10]:
apis.nunique()

47212

In [11]:
A

matrix([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [12]:
B = bg.build_B(**cfg)

Build B
['game_puzzle-45', 'business-91']
game_puzzle-45
get smali
business-91
get smali


In [51]:
B_ = nx.adjacency_matrix(B,apis.unique())

In [52]:
apis.unique()

array(['java/lang/Object;-><init>()V',
       'me/relex/circleindicator/CircleIndicator;->access$100(Lme/relex/circleindicator/CircleIndicator;)Landroid/support/v4/view/ViewPager;',
       'android/support/v4/view/ViewPager;->getAdapter()Landroid/support/v4/view/PagerAdapter;',
       ..., 'playercom/quick/mpsixtyfive/model/Presets;-><init>()V',
       'playercom/quick/mpsixtyfive/model/Presets;->getPresetId()I',
       'playercom/quick/mpsixtyfive/model/Presets;->getOpt()I'],
      dtype=object)

In [53]:
nx.adjacency_matrix(bg.build_B(**cfg), apis.values)

Build B
['entertainment-671', 'house_and_home-25']
entertainment-671
get smali


AttributeError: 'NoneType' object has no attribute 'group'

In [56]:
A*A.T

matrix([[40816, 13713,     0,     0],
        [13713, 28505,     0,     0],
        [    0,     0,     0,     0],
        [    0,     0,     0,     0]])

In [55]:
A.T

matrix([[1, 1, 0, 0],
        [1, 0, 0, 0],
        [1, 1, 0, 0],
        ...,
        [0, 1, 0, 0],
        [0, 1, 0, 0],
        [0, 1, 0, 0]])

In [21]:
bg.main(**cfg)

get info
check malware
['productivity-147', 'game_racing-11', 'b765aff5310466fcea295a3ae9058305', '16b778921b6db27a2af23dd8ce1fac3e']


['productivity-147',
 'game_racing-11',
 'b765aff5310466fcea295a3ae9058305',
 '16b778921b6db27a2af23dd8ce1fac3e']

In [20]:
cfg

{'benign_src': '/home/zjliao/dsc180a/data/smali',
 'mal_src': '/datasets/dsc180a-wi20-public/Malware/amd_data_smali',
 'num_b': 2,
 'num_m': 2}

In [31]:
malware = bg.malware_detection(**cfg)

get info
check malware


In [32]:
malware

In [44]:
A, apis, apks = malware.buildA_matrix()

Build A
lifestyle-12
get smali
game_adventure-82
get smali
7e8e2fd072c4b64f891974636792520e
get smali
019253cd6e33409c29a0546c3217944f
get smali
27307


In [45]:
A

matrix([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [56]:
B_ = nx.adjacency_matrix(malware.build_B(), apis)

Build B
get smali
get smali
get smali
get smali


In [57]:
B_

<27307x27307 sparse matrix of type '<class 'numpy.int64'>'
	with 495482 stored elements in Compressed Sparse Row format>

In [65]:
P_ = nx.adjacency_matrix(malware.build_P(), apis)

Build P
get smali
get smali
get smali
get smali


In [67]:
A*B_*P_*P_.T*B_.T*A.T

matrix([[     1057196,     76613133,            0,            0],
        [    76613133, 232679336483,            0,            0],
        [           0,            0,            0,            0],
        [           0,            0,            0,            0]],
       dtype=int64)