In [1]:
import os,sys,inspect
currentdir = os.path.dirname(os.path.abspath(inspect.getfile(inspect.currentframe())))
parentdir = os.path.dirname(currentdir)
sys.path.insert(0,parentdir) 

In [9]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
import json
import networkx as nx
import lib.build_graph as bg

In [14]:
malware = bg.malware_detection(**cfg)

get info
check malware


In [16]:
A, apis, apks = malware.buildA_matrix()

Build A
personalization-165
get smali
health_and_fitness-138
get smali
070d1c215e7e244026e89a92628bda6a
get smali
11e9fbf897a1327b621fa103ebead210
get smali
24492


In [17]:
A

matrix([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 1, 1, 1],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [20]:
B = nx.adjacency_matrix(malware.build_B(), apis)

Build B
get smali
get smali
get smali
get smali


In [21]:
B

<24492x24492 sparse matrix of type '<class 'numpy.int64'>'
	with 429310 stored elements in Compressed Sparse Row format>

In [22]:
P = nx.adjacency_matrix(malware.build_P(), apis)

Build P
get smali
get smali
get smali
get smali


In [24]:
A*A.T

matrix([[ 7491,  1633,     0,     0],
        [ 1633, 18634,     0,     0],
        [    0,     0,     0,     0],
        [    0,     0,     0,     0]])

In [23]:
A*B*A.T

matrix([[147545, 129659,      0,      0],
        [129659, 323693,      0,      0],
        [     0,      0,      0,      0],
        [     0,      0,      0,      0]], dtype=int64)

In [67]:
A*B_*P_*P_.T*B_.T*A.T

matrix([[     1057196,     76613133,            0,            0],
        [    76613133, 232679336483,            0,            0],
        [           0,            0,            0,            0],
        [           0,            0,            0,            0]],
       dtype=int64)